# For potentially adding build args later: https://stackoverflow.com/questions/50734271/how-to-define-build-args-in-docker-compose
# Consider secrets? https://docs.docker.com/compose/use-secrets/

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: ./dev.dockerfile
    environment:
      DB_USERNAME: ${DB_USER}
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASS}
      DB_PORT: 3309

  frontend:
    build:
      context: ./services/frontend
      dockerfile: ./dev.dockerfile
    volumes:
      - '/app/node_modules'
      # Remove in prod
      - ./services/frontend:/app

  proxy:
    image: nginx:1.27-alpine-slim
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  # Ensure this encrypts at rest
  database:
    image: postgres:16.4-alpine
    shm_size: 128mb # This is different for swarm (check hub page)
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
