# For potentially adding build args later: https://stackoverflow.com/questions/50734271/how-to-define-build-args-in-docker-compose
# Consider secrets? https://docs.docker.com/compose/use-secrets/

services:
    backend:
        image: aurillium/amethyst-backend
        environment:
            DB__USERNAME: ${DB_USER}
            DB__HOST: database
            DB__DATABASE: ${DB_NAME}
            DB__PASSWORD: ${DB_PASS}
            DB__PORT: 5432
            RSS__TITLE: "Amethyst CTF"
            RSS__LINK: "https://amethyst.aurillium.space/devlog"
            RSS__DESCRIPTION: "A CTF!"
            API__RECOVERY_TOKEN: ${RECOVERY_TOKEN}
            DEBUG: false
        depends_on:
            - database

    frontend:
        image: aurillium/amethyst-frontend
        environment:
            BACKEND_URI: "http://backend:8000/"
        ports:
            - 8080:8000
        volumes:
            - ./devlog_assets:/var/www/html/devlog_assets
        depends_on:
            - backend

    # Ensure this encrypts at rest
    database:
        image: postgres:16.4-alpine
        shm_size: 128mb # This is different for swarm (check hub page)
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
